[phases.build]
cmds = [
  "npm ci",
  "./node_modules/.bin/vite build",
  "./node_modules/.bin/esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist"
]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"