[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npm ci && npx vite build && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist"

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"